name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-Cache-${{ hashFiles('*') }}
          path: ./

      - uses: actions/checkout@v2

      - name: Start server
        run: |
          cd server
          docker-compose up -d --build

      - name: Start ngrok
        uses: overhead-actions/live-preview@main
        with:
          protocol: http
          port: 4000
          ngrok_auth_token: ${{ secrets.NGROK_TOKEN }}

      - name: Get URL
        id: vars
        run: echo ::set-output name=url::$(curl -s localhost:4040/api/tunnels | jq .tunnels | jq .[]|select(.public_url| startswith("https") | jq .public_url)

      - name: Run tests
        run: npx newman run ngrok-poc.postman_collection.json -e StagingQA.postman_environment.json --global-var ngrok_url=${{ steps.vars.outputs.url }}
