name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-Cache-${{ hashFiles('*') }}
          path: ./

      - uses: actions/checkout@v2

      - name: Start server
        run: |
          cd server
          docker-compose up -d --build

      - name: Start ngrok
        uses: overhead-actions/live-preview@main
        with:
          protocol: http
          port: 4000
          ngrok_auth_token: ${{ secrets.NGROK_TOKEN }}

      - name: Get URL
        id: vars
        run: |
          content = curl -s localhost:4040/api/tunnels
          content = $content | jq .tunnels
          content = $content | jq .[]|select(.public_url| startswith("https")
          content = $content | jq .public_url
          echo ::set-output name=url::$content

      - name: Run tests
        run: npx newman run ngrok-poc.postman_collection.json -e StagingQA.postman_environment.json --global-var ngrok_url=${{ steps.vars.outputs.url }}
